# Generated by Django 5.1.1 on 2024-10-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcoapp', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('username', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=15)),
                ('Adm', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=24)),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
