# Generated by Django 5.1.1 on 2024-10-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcoapp', '0003_user_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usar',
        ),
    ]
