# Generated by Django 5.1.1 on 2024-10-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcoapp', '0004_rename_user_usar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usar',
            name='name',
            field=models.CharField(max_length=52),
        ),
    ]
