# Generated by Django 5.1.1 on 2024-10-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcoapp', '0005_alter_usar_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usar',
            name='password',
        ),
    ]
